config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :contacts
  root 'posts#index'
  get '/about'=>'pages#about'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
    validates:name, presence:true
    validates:email, presence: true
    validates:message, presence:true
end

app/models/post.rb
class Post < ActiveRecord::Base
 mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

    def new
      @contact = Contact.new
    end
    
    def create
        @contact = Contact.new(contact_params)
        if @contact.save
            name=params[:contact][:name]
            email=params[:contact][:email]
            body=params[:contact][:message]
            ContactMailer.contact_email(name,email,body).deliver_now
            
            flash[:success] = 'Message Sent.'
            redirect_to new_contact_path
        else
            flash[:danger] = 'Error sending message.'
            redirect_to new_contact_path
        end
    end
    private
        def contact_params
        params.require(:contact).permit(:name,:email,:mobile,:message)
        end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
def about
  
end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :image, :remote_image_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/contacts/new.html.erb
<h1>Contact Us</h1>
<div class="col-md-4">
    <div class = "well">
<%=form_for @contact do |f|%>
 
  
 <div class="form-group">
        <div class="field">
            <%= f.label :name %>
            <%= f.text_field :name, class:'form-control', placeholder:'name' %>
        </div>
     </div>
   
    <div class="form-group">
     <div class="field">
        <%= f.label :email %><br>
        <%= f.text_area :email, class:'form-control', placeholder:'email' %>
      </div>
    </div>

    <div class="form-group">
     <div class="field">
        <%= f.label :mobile %><br>
        <%= f.text_area :mobile, class:'form-control', placeholder:'mobile#' %>
      </div>
    </div>
  
    <div class="form-group">
     <div class="field">
        <%= f.label :message %><br>
        <%= f.text_area :message, class:'form-control', placeholder:'type your message here' %>
      </div>
    </div>
    
     <!--<div class="form-group">
     <div class="actions">
        <%= f.submit %>
      </div>
    </div>-->
  
 <%= f.submit 'Submit' %>

<% end %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  

  </ul>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <%= link_to "RubyBlog", root_path, class: "navbar-brand" %>
      
      <!--<a class="navbar-brand" href="#">TheRubyBlog</a>-->
     
  </div>
  <div class="collapse navbar-collapse" id ="main-nav-collapse">
  <ul class="nav navbar-nav navbar-right">
       <li><%= link_to "About Us",about_path, class: "navbar-brand"%></li>
        <li><%= link_to "Contact Us",new_contact_path, class: "navbar-brand"%></li>
  <!--<a class="nav navbar-right" href="/Contact">Contact Us</a>-->
</div>
</div>
</nav>

<div class=container>
  <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
  <%end%>
  <%= yield %>
</div>

</body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

<div>
<h3>This is about page</h3>
</div>

app/views/posts/_form.html.erb
<div class="col-md-4">
    <div class = "well">
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 
     <div class="form-group">
        <div class="field">
            <%= f.label :title %>
            <%= f.text_field :title, class:'form-control', placeholder:'title' %>
        </div>
     </div>
   
    <div class="form-group">
     <div class="field">
        <%= f.label :body %><br>
        <%= f.text_area :body, class:'form-control', placeholder:'body' %>
      </div>
    </div>

  
    <div class="form-group">
      <div>
         <%= f.label :image %>
        <%= f.file_field :image %>
      </div>
    </div>
  
    
    
    <!--<div class="form-group">
     <div class="actions">
        <%= f.submit %>
      </div>
    </div>-->
  
 <%= f.submit %>

<% end %>

</div>
</div>

app/views/posts/_form1.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<form>
 <div class="form-group">
   <div class="col-sm-10">
    
      <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title, class:'form-control', placeholder:'title' %>
      </div>
    </div>
</div>
<div class="form-group">
   <div class="col-sm-10">
     
      <div class="field">
        <%= f.label :body %><br>
        <%= f.text_area :body, class:'form-control', placeholder:'body' %>
      </div>
    </div>
</div>
   <div class="form-group">
   <div class="col-sm-10">
    <p>
      <strong>Image:</strong>
      <%= image_tag @post.image_url(:medium) if @post.image? %>  
    </p>
    </div>
  </div>
  <div class="form-group">
   <div class="col-sm-10">
      <div>
         <%= f.label :image %>
        <%= f.file_field :image %>
      </div>
    </div>
  </div>
  <div class="form-group">
   <div class="col-sm-10">
      <div class="actions">
        <%= f.submit %>
      </div>
    </div>
  </div>
</form>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form1' %>
<div class="form-group">
   <div class="col-sm-10">
        <%= link_to 'Show', @post,class: 'btn btn-default' %>
        <%= link_to 'Back', posts_path,class: 'btn btn-default' %>
    </div>
</div>

app/views/posts/index.html.erb
<!--<p id="notice"><%= notice %></p>-->
<div class="jumbotron text-center">
    <h1>Welcome to Ruby Blog</h1>
    <h3>All the help you can get on Ruby</h3>
</div>
  

<table class='table table-striped'>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Image</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= image_tag post.image_url(:small) if post.image? %></td>
        <td><%= link_to 'Show', post, class: 'btn btn-info' %></td>
        <td><%= link_to 'Edit', edit_post_path(post), class: 'btn btn-warning' %></td>
        <td><%= link_to 'Delete', post, class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path, class: 'btn btn-default' %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>
<div class="col-sm-10">
        <form class="form-horizontal">
                 <%= link_to 'Back', posts_path, class:'btn btn-default' %>
        </form>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<form class="form-horizontal">
  <div class="form-group">
   <div class="col-sm-10">
    <p>
      <strong>Title:</strong>
      <%= @post.title %>
    </p>
    </div>
  </div>

  <div class="form-group">
   <div class="col-sm-10">
    <p>
      <strong>Body:</strong>
      <%= @post.body %>
    </p>
    </div>
  </div>
  <div class="form-group">
   <div class="col-sm-10">
    <p>
      <strong>Image:</strong>
      <%= image_tag @post.image_url(:medium) if @post.image? %>  
    </p>
    </div>
  </div>


<!--<%= link_to 'Edit', edit_post_path(@post),class: 'btn btn-default' %>-->
<%= link_to 'Back', posts_path,class: 'btn btn-default' %>
</form>